# Generated by Django 5.2.12 on 2026-03-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('user', 'User Generated')], default='user', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('avatar_color', models.CharField(default='#7c3aed', max_length=32)),
                ('strength', models.PositiveIntegerField(default=50)),
                ('speed', models.PositiveIntegerField(default=50)),
                ('durability', models.PositiveIntegerField(default=50)),
                ('intelligence', models.PositiveIntegerField(default=50)),
                ('max_health', models.PositiveIntegerField(default=100)),
                ('passive_name', models.CharField(blank=True, max_length=120)),
                ('passive_description', models.TextField(blank=True)),
                ('abilities', models.JSONField(blank=True, default=list)),
                ('win_condition', models.TextField(blank=True)),
                ('balance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('seed', models.CharField(blank=True, max_length=80)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('sim_count', models.PositiveIntegerField(default=1)),
                ('fighter_a_wins', models.PositiveIntegerField(default=0)),
                ('fighter_b_wins', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fighter_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_as_a', to='arena.character')),
                ('fighter_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_as_b', to='arena.character')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='arena.character')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
