# Generated by Django 5.2.12 on 2026-04-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_seed_default_champions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(blank=True, choices=[('bug', 'Bug'), ('display', 'Display or layout'), ('account', 'Account or access'), ('performance', 'Performance'), ('other', 'Other')], max_length=24)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.CharField(max_length=160)),
                ('details', models.TextField(max_length=4000)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('blocking', 'Blocking')], max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('build_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
